menu:
# - {name: 'Home', url: '/'}
# - {name: 'about', url: '/about'}
- {name: 'Articles', url: 'articles'}
- {name: 'Portfolio', url: 'portfolio'}
# - {name: 'gallery', url: '/gallery'}
# - {name: 'contact', url: '/contact'}
# - {name: 'search', url: '/search'}

gallery:
- {location: '蘭嶼', year: '2020', url: 'lanyu.webp', description: 
  '<p>2020 年的暑假我跟爸媽一起去了蘭嶼，這張照片拍攝於當地的一處露營地，當時似乎不是旺季，露營地裡一組客人都沒有，但老闆很好心地讓我們進去參觀。</p>
  <p>這幾張椅子被擺在艷陽高照的蘭嶼海邊，海浪的聲音很大，在強光的照射之下一切似乎都變得有些不飽和。</p>
  <p>上個星期應該有一些學生坐在這邊看海吧。</p>'}
- {location: '蘭嶼', year: '2020', url: 'island.webp', description: 
  '<p>這張照片也同樣拍攝於蘭嶼，當下具體的情況是什麼樣子的已經記不清了，但那天的陽光在海面的映射之下，形成了一種很特別的顏色。</p>
  <p>在最後所遺留下來的往往都只是像這樣的「印象」而已。</p>'}
- {location: '桃園', year: '2020', url: 'sunset.webp', description:
  '<p>從我房間眺望出去就是這樣的情景，那天的晚霞呈現一種不可思議的顏色。大樓的剪影失去了深度，好像紙卡一般。</p>'}
- {location: '台灣大學', year: '2020', url: 'house.webp', description:
  '<p>每天上學都會經過這棟似乎是教職員宿舍的小屋，但看不出目前有沒有人在住。</p>
  <p>屋外的綠葉與屋內依稀可辨的紅色房門，是我一直都很想捕捉的鏡頭。</p>'}
- {location: '台灣大學', year: '2019', url: 'door.webp', description:
  '<p><span style="font-size: 14px;">「我的房間有兩個門。一個是入口，一個是出口。沒有互換性。從入口出不去，從出口進不來。這是一定的。人們從入口進來，從出口出去。有各種進來的方式，各種出去的方式。但不管怎麼樣，大家都會出去。⋯⋯已經離去的人。他們口中說出過的話，他們的氣息，他們所哼唱的歌，我可以看得見像塵埃一般飄在房間的每個角落。」</span>
  <span style="float: right; font-size: 14px;">──《 舞．舞．舞 》</span></p>'}
- {location: '千手ヶ浜', year: '2019', url: 'nikko.webp', description:
  '<p>那天稍微有點霧氣，並且下著小雨。</p>
  <p>要進入到位於管制區內的千手ヶ浜只能依靠遊覽車，且此時正處淡季，中禅寺湖的遊湖船也不會停靠在這裡。就這樣，視野內看不到任何一個人，空氣中響起的也只有潺潺的水聲。</p>
  <p>那是宛如世界末日一般的情境，而這些座落在湖畔的桌椅們就像是人類所留下的遺跡。</p>'}
- {location: '日暮里', year: '2019', url: 'trainstation.webp', description:
  '<p>我們沿著山坡上的一條便道，準備去搭電車。平常看起來先進的車站從上方看時竟然顯得有些簡陋，就像一間已經有些破敗的工廠。</p>
  <p>在鐵絲網後頭提著公事包快步走著的上班族在這時看起來就像遊走於各個生產線上的工人一般。</p>
  <p>或許確實是這樣呢，在高度資本主義社會下，一切都機械化了、僵硬化了，不是嗎？</p>'}
- {location: '池袋', year: '2019', url: 'dawn.webp', description:
  '<p>今天要陪同學們去搭飛機，大家都起了個大早，準備收拾雜亂不堪的行李。</p>
  <p>在天剛亮的池袋，一切都還很安靜，陰影下的建築物們看起來並不是太有精神的樣子。</p>
  <p>在大家的夢都還沒醒時，我們已經準備要坐上飛機，過了這個暑假，我們就是大學生了，一切會如何變化呢？我們當時都還沒有把握。</p>'}
- {location: '湘南海岸', year: '2019', url: 'coast.webp', description:
  '<p>在湘南海岸的那個晚上，下起了毛毛雨。海風很冷，但我們還是沿著海岸邊的公路，慢慢地走。</p>
  <p>這是那天在準備走回民宿，跨過江之電的軌道前，我所拍的最後一張照片。</p>'}
- {location: '湘南海岸', year: '2019', url: 'surf.webp', description:
  '<p>我們從藤澤開始，沿著海岸線，準備前往在《 舞．舞．舞 》中有出現過的辻堂海濱公園。</p>
  <p>到處都充滿著衝浪的人群，有很多人會把衝浪板綁在腳踏車的側邊，穿著拖鞋，就準備騎去海邊衝浪。</p>
  <p>那天的天氣不是很好。灰色的天空、灰色的海、灰色的屋舍、灰色的沙，衝浪板的色彩在這時顯得耀眼奪目。</p>'}

social:
  - {icon: 
     '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.58.82-2.14-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.14 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
  </svg>',link: 'https://github.com/sreedeepEK'}
    
  - {icon: '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
      <path d="M0 1.146C0 .513.324 0 .725 0h14.55c.401 0 .725.513.725 1.146v13.708c0 .633-.324 1.146-.725 1.146H.725A.723.723 0 0 1 0 14.854V1.146zm4.943 12.248V6.169H3.09v7.225h1.854zm-.928-8.21c.837 0 1.516-.679 1.516-1.516a1.516 1.516 0 1 0-3.032 0c0 .837.679 1.516 1.516 1.516zM6.18 6.169v7.225h1.853V9.359c0-.515.093-.998.64-1.374.476-.333 1.12-.22 1.509.191v4.217h1.853V9.13c0-1.562-1.146-2.302-2.675-2.302-1.299 0-1.907.669-2.23 1.113h-.033V6.169H6.18z"/>
      </svg>', link: 'https://linkedin.com/in/sreedeepek'}
# - {icon:
#   '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
#   <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
# </svg>', link: 'https://www.facebook.com/haoyong0309'}

contacts:
- {name: '翁浩永', title: '23rd 社長', department: '台大咖啡社', institution: '資訊工程系', institution_address: '台灣大學', phone: '(000) 000-0000', email: 'tim0309.tw@gmail.com', office: 'Science Building 505', image: 'assets/img/about.JPG'}
